### ISSUE TITLE
Compatibility with Pillow >= 10.0.0 (roomba directory)

### ISSUE THREAD

**Issue by marillat** [FilipDem/Domoticz-iROBOT-ROOMBA-plugin#9]
I noticed this PR https://github.com/NickWaterton/Roomba980-Python/pull/120
as the current roomba directory display 
```
  File "/opt/domoticz/plugins/Roomba/roomba/roomba.py", line 206, in create_icon
    icon = self.base_icon.copy().resize(size,Image.ANTIALIAS)
                                             ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

```

**Comment by marillat** [comment]
After I applied PR https://github.com/NickWaterton/Roomba980-Python/pull/120
I see 
```
systemd[1]: Started roomba.service - Roomba mqtt client.
python3[231821]: Traceback (most recent call last):
python3[231821]:   File "<frozen runpy>", line 198, in _run_module_as_main
python3[231821]:   File "<frozen runpy>", line 88, in _run_code
python3[231821]:   File "/opt/domoticz/plugins/Roomba/roomba/__main__.py", line 4, in <module>
python3[231821]:     main()
python3[231821]:   File "/opt/domoticz/plugins/Roomba/roomba/roomba_direct.py", line 406, in main
python3[231821]:     myroomba =  Roomba(addr,
python3[231821]:                 ^^^^^^^^^^^^
python3[231821]:   File "/opt/domoticz/plugins/Roomba/roomba/roomba.py", line 454, in __init__
python3[231821]:     self.is_connected = asyncio.Event(loop=self.loop)
python3[231821]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python3[231821]: TypeError: Event.__init__() got an unexpected keyword argument 'loop'
python3[231821]: CV or numpy module not found, falling back to PIL
python3[231821]: CV or numpy module not found, falling back to PIL

```

**Comment by FilipDem** [comment]
I already had a more recent version of my implementation running locally... I updated GitHub with this version.
This one is using LANCZOS... 
I didn't investigating in detail, but I assume this will do the trick...

**Comment by marillat** [comment]
Thanks @FilipDem 

This plugin (or Nick' code) is supposed to be compatible with paho.mqtt 2 ?

**Comment by marillat** [comment]
I confirm doesn't work with paho.mqtt 2.0.0

**Comment by FilipDem** [comment]
I am using paho.mqtt 2.1.0.

pi@Domoticz:~ $ sudo pip3 show paho.mqtt
Name: paho-mqtt
Version: 2.1.0
Summary: MQTT version 5.0/3.1.1 client class
Home-page: None
Author: None
Author-email: Roger Light <roger@atchoo.org>
License: EPL-2.0 OR BSD-3-Clause
Location: /usr/local/lib/python3.9/dist-packages

**Comment by marillat** [comment]
I'm  under  Debian unstable amd64 python 3.12.7 and we only have python3-paho-mqtt 2.0.0 installed apt-get
Not really a problem as we have 1.6.1 in stable.

I've another question.  The roomba service is supposed to **only** work if mosquito is configured with `allow_anonymous true` ?
